
import java.awt.Color;
import static java.lang.String.format;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nachus
 */
public class LoanAssistant extends javax.swing.JFrame {

   
    private Object computePayment;
    double loan;
    double interest;
    double month;
    double payment;
    double MonthlyPayment;
     
     
    public LoanAssistant() {
        initComponents();
        AnalysisButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        balanceField = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BalanceField = new javax.swing.JTextField();
        InterestField = new javax.swing.JTextField();
        PaymentField = new javax.swing.JTextField();
        MonthField = new javax.swing.JTextField();
        ComputeButton = new javax.swing.JButton();
        AnalysisButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        ExitButton = new javax.swing.JButton();
        LoanAnalysisLabel = new javax.swing.JLabel();
        XPaymentButton = new javax.swing.JButton();
        XMonthButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Assistant Project");
        setResizable(false);

        balanceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        balanceField.setText("Loan Balance:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Interest Rate:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Number of Payment:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Monthly Payment:");

        BalanceField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BalanceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceFieldActionPerformed(evt);
            }
        });

        InterestField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        InterestField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterestFieldActionPerformed(evt);
            }
        });

        PaymentField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        MonthField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MonthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MonthFieldActionPerformed(evt);
            }
        });

        ComputeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ComputeButton.setText("Computing Monthly Payment");
        ComputeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComputeButtonActionPerformed(evt);
            }
        });

        AnalysisButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        AnalysisButton.setText("New Loan Analysis");
        AnalysisButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnalysisButtonActionPerformed(evt);
            }
        });

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane2.setViewportView(textArea);

        ExitButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        LoanAnalysisLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LoanAnalysisLabel.setText("Loan Analysis");

        XPaymentButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        XPaymentButton.setText("x");
        XPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XPaymentButtonActionPerformed(evt);
            }
        });

        XMonthButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        XMonthButton.setText("x");
        XMonthButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XMonthButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(balanceField)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BalanceField)
                            .addComponent(InterestField)
                            .addComponent(PaymentField)
                            .addComponent(MonthField, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AnalysisButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ComputeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(XPaymentButton)
                            .addComponent(XMonthButton))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoanAnalysisLabel))
                        .addContainerGap(73, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LoanAnalysisLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balanceField)
                            .addComponent(BalanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(InterestField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(PaymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(XPaymentButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(MonthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(XMonthButton))
                        .addGap(57, 57, 57)
                        .addComponent(ComputeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AnalysisButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MonthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MonthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MonthFieldActionPerformed

    private void InterestFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterestFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InterestFieldActionPerformed

    private void BalanceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BalanceFieldActionPerformed

    @SuppressWarnings("MalformedFormatString")
    private void ComputeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComputeButtonActionPerformed
        // TODO add your handling code here:
        String iMonthPayment = String.format(MonthField.getText());
        if(balanceField.getText().equals("")){
           JOptionPane.showMessageDialog(null, "You must enter amount of Balance)",
                   "Loan Systems" ,JOptionPane.INFORMATION_MESSAGE);
           
        }else{
            loan = Double.parseDouble(balanceField.getText());
            String Balance = String.format(balanceField.getText());
            
        }
        if(InterestField.getText().equals("")){
           JOptionPane.showMessageDialog(null, "You must enter amount of Interest)",
                   "Loan Systems" ,JOptionPane.INFORMATION_MESSAGE);
           
        }else{
            interest = Double.parseDouble(InterestField.getText());
            String Balance = String.format(InterestField.getText());
    }//GEN-LAST:event_ComputeButtonActionPerformed
        if(PaymentField.getText().equals("")){
           JOptionPane.showMessageDialog(null, "You must enter amount of Payment)",
                   "Loan Systems" ,JOptionPane.INFORMATION_MESSAGE);
           
        }else{
            payment = Double.parseDouble(PaymentField.getText());
            String Balance = String.format(balanceField.getText());
        }
        payment = loan+((loan*interest)/100);
        MonthlyPayment = payment/month;
        String String = null;
        String PayMonth = String.format("%,2t",MonthlyPayment);
        MonthField.setText(PayMonth);
        textArea.append("\t\n Loan Assistant Project:\n\n"
                + "Amount of Loan:\t\t 0"+ loan +
                "\n Number of Payment:\t\t  0"+interest +
                "\nMonthly Payment \t\t 0"+month+
                "\nPayment per Month:\t\t 0"+MonthlyPayment+
                "\nTotal Loan Payment \t\t 0"+ payment +
                "\n\nThanks for using this loan System");
        AnalysisButton.setEnabled(true);
        ComputeButton.setEnabled(false);
        
        
    }
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
       System.exit(0);        
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void AnalysisButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnalysisButtonActionPerformed
        // TODO add your handling code here:
        balanceField.setText("");
        InterestField.setText("");
        PaymentField.setText("");
        textArea.setText("");
        AnalysisButton.setEnabled(false);
        ComputeButton.setEnabled(true);
        
        
    }//GEN-LAST:event_AnalysisButtonActionPerformed

    private void XPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XPaymentButtonActionPerformed
        // TODO add your handling code here:
        boolean computePayment = true;
        XPaymentButton.setVisible(false);
        XMonthButton.setVisible(true);
        MonthField.setEditable(true);
        MonthField.setBackground(Color.WHITE);
        MonthField.setFocusable(true);
        PaymentField.setEditable(false);
        PaymentField.setBackground(Color.YELLOW);
        PaymentField.setFocusable(true);
        balanceField.requestFocus();
        
    }//GEN-LAST:event_XPaymentButtonActionPerformed

    private void XMonthButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XMonthButtonActionPerformed
        // TODO add your handling code here:
        boolean computePayment = false;
        XPaymentButton.setVisible(true);
        XMonthButton.setVisible(false);
        MonthField.setEditable(false);
        MonthField.setBackground(Color.YELLOW);
        MonthField.setFocusable(false);
        PaymentField.setEditable(true);
        PaymentField.setBackground(Color.WHITE);
        PaymentField.setFocusable(true);
        balanceField.requestFocus();
        ComputeButton.setVisible(true);
    }//GEN-LAST:event_XMonthButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAssistant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAssistant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnalysisButton;
    private javax.swing.JTextField BalanceField;
    private javax.swing.JButton ComputeButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField InterestField;
    private javax.swing.JLabel LoanAnalysisLabel;
    private javax.swing.JTextField MonthField;
    private javax.swing.JTextField PaymentField;
    private javax.swing.JButton XMonthButton;
    private javax.swing.JButton XPaymentButton;
    private javax.swing.JLabel balanceField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
